### ISSUE TITLE
Can't replant

### ISSUE THREAD

**Issue by ElweThor** [Ch0z/CropReplant#7]
1. defined a key to replant: customReplantKey = P
2. used the Cultivator
3. selected the Seed onion as target to replant, having 150 onions into inventory
4. targeted a seed onion on ground, to replant
5. pressed P
6. nothing changed to onion seed but received the following error in the Log:

```
[Error  : Unity Log] MissingMethodException: void Player.ConsumeResources(Piece/Requirement[],int)
Stack trace:
CropReplant.PlayerPatches.PlayerUpdate_Patch.Postfix (Player __instance) (at <c02e7d738b3d48c897d3464eb0140fb8>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)
```

Nothing changed into inventory too.

**Comment by Ch0z** [comment]
Hi, what version do you use?

EDIT : It looks like an already solved issue. Issue found 2.2.1 with mistland update, fixed in the version 2.2.2
